version: 3

tasks:
  default:
    - task --list-all

  create:
    cmds:
      - |
        cd opentofu
        tofu apply -auto-approve

  destroy:
    cmds:
      - |
        cd opentofu
        tofu destroy -auto-approve

  ansible:
    cmds:
      - |
        cd ansible
        ansible-playbook cluster.yaml

  wsk-setup:
    cmds:
      - |
        HOST="$(awk 'NR==2 {print $2}' ./ansible/hosts.ini | cut -d'=' -f2)"
        wsk -i property set --apihost ${HOST} --auth 23bc46b1-71f6-4ed5-8c54-816aa4f8c502:123zO3xZCLrMN6v2BKK1dXYFpXlPkccOFqm12CdAsMgRU4VrNZ9lyGVCGuMDGIwP

  setup:
    cmds:
      - task: create
      - sleep 120
      - task: ansible
      - task: wsk-setup
      - sleep 420
      - task: create-functions
